version: '3.8'

networks:
  mongodb-network:
    driver: bridge

volumes:
  config-server-1-data:
  config-server-2-data:
  config-server-3-data:
  shard-1-node-1-data:
  shard-1-node-2-data:
  shard-1-node-3-data:
  shard-2-node-1-data:
  shard-2-node-2-data:
  shard-2-node-3-data:

x-mongodb-config: &mongodb-config
  image: mongo:7.0-jammy
  networks:
    - mongodb-network
  environment: &mongodb-env
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER:-admin}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWD:-veryStringPassword}

x-config-server: &config-server-base
  <<: *mongodb-config
  command: mongod --configsvr --replSet config-replica-set --port 27019 --keyFile /etc/mongodb/pki/keyfile
  deploy: &config-resources
    resources:
      limits:
        cpus: '1'
        memory: 1G
      reservations:
        cpus: '0.5'
        memory: 512M

x-shard-node: &shard-node-base
  <<: *mongodb-config
  deploy: &shard-resources
    resources:
      limits:
        cpus: '2'
        memory: 2G
      reservations:
        cpus: '1'
        memory: 1G

services:
  # Config servers
  config-server-1:
    <<: *config-server-base
    hostname: config-server-1
    volumes:
      - config-server-1-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-configserver.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27019:27019"

  config-server-2:
    <<: *config-server-base
    hostname: config-server-2
    volumes:
      - config-server-2-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  config-server-3:
    <<: *config-server-base
    hostname: config-server-3
    volumes:
      - config-server-3-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Router (mongos)
  router-1:
    <<: *mongodb-config
    hostname: router-1
    command: mongos --configdb config-replica-set/config-server-1:27019,config-server-2:27019,config-server-3:27019 --bind_ip_all --port 27017 --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27017:27017"
    deploy: *config-resources
    volumes:
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-router.js:/docker-entrypoint-initdb.d/init-router.js
      - ./scripts/mongo/init-collections.js:/docker-entrypoint-initdb.d/init-collections.js
    depends_on:
      - config-server-1
      - config-server-2
      - config-server-3

  router-2:
    <<: *mongodb-config
    hostname: router-2
    command: mongos --configdb config-replica-set/config-server-1:27019,config-server-2:27019,config-server-3:27019 --bind_ip_all --port 27017 --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27027:27017"
    deploy: *config-resources
    volumes:
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
    depends_on:
      - config-server-1
      - config-server-2
      - config-server-3

  # Shard 1
  shard-1-node-1:
    <<: *shard-node-base
    hostname: shard-1-node-1
    command: mongod --shardsvr --replSet shard-1 --port 27018 --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard-1-node-1-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-shard1.js:/docker-entrypoint-initdb.d/init.js

  shard-1-node-2:
    <<: *shard-node-base
    hostname: shard-1-node-2
    command: mongod --shardsvr --replSet shard-1 --port 27018 --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard-1-node-2-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  shard-1-node-3:
    <<: *shard-node-base
    hostname: shard-1-node-3
    command: mongod --shardsvr --replSet shard-1 --port 27018 --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard-1-node-3-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Shard 2
  shard-2-node-1:
    <<: *shard-node-base
    hostname: shard-2-node-1
    command: mongod --shardsvr --replSet shard-2 --port 27018 --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard-2-node-1-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-shard2.js:/docker-entrypoint-initdb.d/init.js

  shard-2-node-2:
    <<: *shard-node-base
    hostname: shard-2-node-2
    command: mongod --shardsvr --replSet shard-2 --port 27018 --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard-2-node-2-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  shard-2-node-3:
    <<: *shard-node-base
    hostname: shard-2-node-3
    command: mongod --shardsvr --replSet shard-2 --port 27018 --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard-2-node-3-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Monitoring
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mongodb-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mongodb-network
    depends_on:
      - prometheus