version: '3.8'

networks:
  mongodb-network:
    driver: bridge

volumes:
  cfgsvr1-data:
  cfgsvr2-data:
  cfgsvr3-data:
  shard1-1-data:
  shard1-2-data:
  shard1-3-data:
  shard2-1-data:
  shard2-2-data:
  shard2-3-data:
  cfgsvr1-config:
  cfgsvr2-config:
  cfgsvr3-config:
  shard1-1-config:
  shard1-2-config:
  shard1-3-config:
  shard2-1-config:
  shard2-2-config:
  shard2-3-config:

x-mongodb-config: &mongodb-config
  image: mongo:7.0-jammy
  networks:
    - mongodb-network
  environment: &mongodb-env
    MONGO_INITDB_DATABASE: admin
    DB_USERNAME: admin
    DB_PASSWORD: admin

x-config-server: &config-server-base
  <<: *mongodb-config
  command: mongod --configsvr --replSet config-replica-set --port 27019 --keyFile /etc/mongodb/pki/keyfile
  deploy: &config-resources
    resources:
      limits:
        cpus: '1'
        memory: 1G
      reservations:
        cpus: '0.5'
        memory: 512M

x-shard-node: &shard-node-base
  <<: *mongodb-config
  deploy: &shard-resources
    resources:
      limits:
        cpus: '2'
        memory: 2G
      reservations:
        cpus: '1'
        memory: 1G

services:
  # Config servers
  cfgsvr1:
    <<: *config-server-base
    hostname: cfgsvr1
    container_name: mongo-config-01
    command: >-
      mongod --configsvr 
      --replSet cfgrs 
      --port 27019 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
      --wiredTigerCacheSizeGB 1
      --oplogSize 1024
      --setParameter diagnosticDataCollectionEnabled=true
      --setParameter enableLocalhostAuthBypass=false
    volumes:
      - cfgsvr1-data:/data/db
      - cfgsvr1-config:/data/configdb
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-configserver.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27019:27019"
    healthcheck:
      test: mongosh --port 27019 --eval "rs.status()" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      - shard1-1
      - shard2-1

  cfgsvr2:
    <<: *config-server-base
    hostname: cfgsvr2
    container_name: mongo-config-02
    command: >-
      mongod --configsvr 
      --replSet cfgrs 
      --port 27019 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
      --wiredTigerCacheSizeGB 1
      --oplogSize 1024
      --setParameter diagnosticDataCollectionEnabled=true
      --setParameter enableLocalhostAuthBypass=false
    volumes:
      - cfgsvr2-data:/data/db
      - cfgsvr2-config:/data/configdb
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
    restart: always
    depends_on:
      - shard1-1
      - shard2-1

  cfgsvr3:
    <<: *config-server-base
    hostname: cfgsvr3
    container_name: mongo-config-03
    command: >-
      mongod --configsvr 
      --replSet cfgrs 
      --port 27019 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
      --wiredTigerCacheSizeGB 1
      --oplogSize 1024
      --setParameter diagnosticDataCollectionEnabled=true
      --setParameter enableLocalhostAuthBypass=false
    volumes:
      - cfgsvr3-data:/data/db
      - cfgsvr3-config:/data/configdb
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
    restart: always
    depends_on:
      - shard1-1
      - shard2-1

  # Router (mongos)
  router-1:
    <<: *mongodb-config
    hostname: router-1
    command: mongos --configdb cfgrs/cfgsvr1:27019,cfgsvr2:27019,cfgsvr3:27019 --bind_ip_all --port 27017 --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27017:27017"
    deploy: *config-resources
    volumes:
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-router.js:/docker-entrypoint-initdb.d/init-router.js
      - ./scripts/mongo/init-collections.js:/docker-entrypoint-initdb.d/init-collections.js
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3

  router-2:
    <<: *mongodb-config
    hostname: router-2
    command: mongos --configdb cfgrs/cfgsvr1:27019,cfgsvr2:27019,cfgsvr3:27019 --bind_ip_all --port 27017 --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27027:27017"
    deploy: *config-resources
    volumes:
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3

  # Shard 1
  shard1-1:
    <<: *shard-node-base
    hostname: shard1-1
    container_name: shard-01-node-a
    command: >-
      mongod --replSet shard1rs 
      --shardsvr 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27018:27018"  # Add explicit port mapping
    volumes:
      - shard1-1-data:/data/db
      - shard1-1-config:/data/configdb
      - ./scripts:/scripts
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-shard1.js:/docker-entrypoint-initdb.d/init.js
    restart: always
    links:
      - shard1-2
      - shard1-3
    healthcheck:
      test: mongosh --port 27018 --eval "rs.status()" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  shard1-2:
    <<: *shard-node-base
    hostname: shard1-2
    container_name: shard-01-node-b
    command: >-
      mongod --shardsvr 
      --replSet shard1rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard1-2-data:/data/db
      - shard1-2-config:/data/configdb
      - ./scripts:/scripts
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
    restart: always

  shard1-3:
    <<: *shard-node-base
    hostname: shard1-3
    command: >-
      mongod --shardsvr 
      --replSet shard1rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard1-3-data:/data/db
      - shard1-3-config:/data/configdb
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Shard 2
  shard2-1:
    <<: *shard-node-base
    hostname: shard2-1
    container_name: shard-02-node-a
    command: >-
      mongod --shardsvr 
      --replSet shard2rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27028:27018"  # Add explicit port mapping
    volumes:
      - shard2-1-data:/data/db
      - shard2-1-config:/data/configdb
      - ./scripts:/scripts
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-shard2.js:/docker-entrypoint-initdb.d/init.js
    restart: always
    links:
      - shard2-2
      - shard2-3

  shard2-2:
    <<: *shard-node-base
    hostname: shard2-2
    command: >-
      mongod --shardsvr 
      --replSet shard2rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard2-2-data:/data/db
      - shard2-2-config:/data/configdb
      - ./scripts:/scripts
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  shard2-3:
    <<: *shard-node-base
    hostname: shard2-3
    command: >-
      mongod --shardsvr 
      --replSet shard2rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard2-3-data:/data/db
      - shard2-3-config:/data/configdb
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Monitoring
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mongodb-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mongodb-network
    depends_on:
      - prometheus