version: '3.8'

networks:
  mongodb-network:
    driver: bridge

volumes:
  cfgsvr1-data:
  cfgsvr2-data:
  cfgsvr3-data:
  shard1-1-data:
  shard1-2-data:
  shard1-3-data:
  shard2-1-data:
  shard2-2-data:
  shard2-3-data:

x-mongodb-config: &mongodb-config
  image: mongo:7.0-jammy
  networks:
    - mongodb-network
  environment: &mongodb-env {}

x-config-server: &config-server-base
  <<: *mongodb-config
  command: mongod --configsvr --replSet config-replica-set --port 27019 --keyFile /etc/mongodb/pki/keyfile
  deploy: &config-resources
    resources:
      limits:
        cpus: '1'
        memory: 1G
      reservations:
        cpus: '0.5'
        memory: 512M

x-shard-node: &shard-node-base
  <<: *mongodb-config
  deploy: &shard-resources
    resources:
      limits:
        cpus: '2'
        memory: 2G
      reservations:
        cpus: '1'
        memory: 1G

services:
  # Config servers
  cfgsvr1:
    <<: *config-server-base
    hostname: cfgsvr1
    command: >-
      mongod --configsvr 
      --replSet cfgrs 
      --port 27019 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - cfgsvr1-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-configserver.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27019:27019"
    healthcheck:
      test: mongosh --port 27019 --eval "rs.status()" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  cfgsvr2:
    <<: *config-server-base
    hostname: cfgsvr2
    volumes:
      - cfgsvr2-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  cfgsvr3:
    <<: *config-server-base
    hostname: cfgsvr3
    volumes:
      - cfgsvr3-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Router (mongos)
  router-1:
    <<: *mongodb-config
    hostname: router-1
    command: mongos --configdb cfgrs/cfgsvr1:27019,cfgsvr2:27019,cfgsvr3:27019 --bind_ip_all --port 27017 --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27017:27017"
    deploy: *config-resources
    volumes:
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-router.js:/docker-entrypoint-initdb.d/init-router.js
      - ./scripts/mongo/init-collections.js:/docker-entrypoint-initdb.d/init-collections.js
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3

  router-2:
    <<: *mongodb-config
    hostname: router-2
    command: mongos --configdb cfgrs/cfgsvr1:27019,cfgsvr2:27019,cfgsvr3:27019 --bind_ip_all --port 27017 --keyFile /etc/mongodb/pki/keyfile
    ports:
      - "27027:27017"
    deploy: *config-resources
    volumes:
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3

  # Shard 1
  shard1-1:
    <<: *shard-node-base
    hostname: shard1-1
    command: >-
      mongod --replSet shard1rs 
      --shardsvr 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard1-1-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-shard1.js:/docker-entrypoint-initdb.d/init.js
    healthcheck:
      test: mongosh --port 27018 --eval "rs.status()" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  shard1-2:
    <<: *shard-node-base
    hostname: shard1-2
    command: >-
      mongod --shardsvr 
      --replSet shard1rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard1-2-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  shard1-3:
    <<: *shard-node-base
    hostname: shard1-3
    command: >-
      mongod --shardsvr 
      --replSet shard1rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard1-3-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Shard 2
  shard2-1:
    <<: *shard-node-base
    hostname: shard2-1
    command: >-
      mongod --shardsvr 
      --replSet shard2rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard2-1-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./scripts/mongo/init-shard2.js:/docker-entrypoint-initdb.d/init.js

  shard2-2:
    <<: *shard-node-base
    hostname: shard2-2
    command: >-
      mongod --shardsvr 
      --replSet shard2rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard2-2-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  shard2-3:
    <<: *shard-node-base
    hostname: shard2-3
    command: >-
      mongod --shardsvr 
      --replSet shard2rs 
      --port 27018 
      --bind_ip_all 
      --keyFile /etc/mongodb/pki/keyfile
    volumes:
      - shard2-3-data:/data/db
      - ./scripts/mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  # Monitoring
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mongodb-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mongodb-network
    depends_on:
      - prometheus